// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYtZW40M-tkgJ3VaDnBT_mJCEYMqVZofI',
    appId: '1:1021975197599:web:b637f2cafddef63bf72faa',
    messagingSenderId: '1021975197599',
    projectId: 'nametickles',
    authDomain: 'nametickles.firebaseapp.com',
    storageBucket: 'nametickles.appspot.com',
    measurementId: 'G-NMVQJF8P56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp9nIHw3Cz9Imv7xwnCHMxwYgFUTnqIyI',
    appId: '1:1021975197599:android:e5dffa9391edebb6f72faa',
    messagingSenderId: '1021975197599',
    projectId: 'nametickles',
    storageBucket: 'nametickles.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYtZW40M-tkgJ3VaDnBT_mJCEYMqVZofI',
    appId: '1:1021975197599:web:09c3bacb35833353f72faa',
    messagingSenderId: '1021975197599',
    projectId: 'nametickles',
    authDomain: 'nametickles.firebaseapp.com',
    storageBucket: 'nametickles.appspot.com',
    measurementId: 'G-FDB7K8F7M1',
  );
}
